# shopify.app.toml
name = "React Router"
client_id = "702ade2bec98d9b1fe514e134598255d"
application_url = "https://arctic-forecast-every-eva.trycloudflare.com"
embedded = false

[auth]
redirect_urls = ["https://arctic-forecast-every-eva.trycloudflare.com/auth/callback"]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://arctic-forecast-every-eva.trycloudflare.com"
subpath = "videos"
prefix = "apps"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
