# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9eed658576b691e3cb3aa51c5c23546a"
name = "EE-App"
application_url = "https://available-injured-authorization-addressing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_products,write_app_proxy,write_files,write_products"

[auth]
redirect_urls = [
  "https://available-injured-authorization-addressing.trycloudflare.com/api/auth"
]

[app_proxy]
url = "https://available-injured-authorization-addressing.trycloudflare.com/api/carousel-videos"
subpath = "carousel-videos"
prefix = "a"
